package com.example.textsocial.feed.service;
import com.example.textsocial.feed.client.SocialInternalClient;
import com.example.textsocial.feed.client.SocialInternalClient.ContentView;
import com.example.textsocial.feed.domain.*; import com.example.textsocial.feed.repository.*;
import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service;
@Service public class FeedService {
 private final TimelineRepository timelines; private final AuthorPostRepository authors; private final SocialInternalClient social; private final int days;
 public FeedService(TimelineRepository t,AuthorPostRepository a,SocialInternalClient s,@Value("${app.feed-lookback-days:7}")int d){timelines=t;authors=a;social=s;days=d;}
 public FeedPage feed(UUID user,String cursor,int limit){int n=Math.min(20,Math.max(1,limit)); Cursor after=Cursor.decode(cursor); Map<UUID,SortKey> all=new HashMap<>(); LocalDate today=LocalDate.now(ZoneOffset.UTC); for(int i=0;i<days;i++){LocalDate d=today.minusDays(i);timelines.findBucket(user,d).forEach(e->all.putIfAbsent(e.getKey().getPostId(),new SortKey(e.getKey().getPostId(),e.getKey().getCreatedAt())));} List<UUID> celebs=new ArrayList<>(social.celebrities(user)); celebs.add(user); for(UUID author:celebs)for(int i=0;i<days;i++)authors.findBucket(author,today.minusDays(i)).forEach(e->all.putIfAbsent(e.getKey().getPostId(),new SortKey(e.getKey().getPostId(),e.getKey().getCreatedAt()))); List<SortKey> ordered=all.values().stream().filter(k->after==null||k.before(after)).sorted(Comparator.comparing(SortKey::time).reversed().thenComparing(k->k.id().toString())).limit(n+1).toList(); boolean more=ordered.size()>n;if(more)ordered=ordered.subList(0,n);List<UUID> ids=ordered.stream().map(SortKey::id).toList();List<ContentView> views=ids.isEmpty()?List.of():social.batch(new SocialInternalClient.BatchRequest(ids,user));Map<UUID,ContentView> map=new HashMap<>();views.forEach(v->map.put(v.id(),v));return new FeedPage(ids.stream().map(map::get).filter(Objects::nonNull).toList(),more?Cursor.encode(ordered.get(ordered.size()-1)):null);}
 private record SortKey(UUID id,Instant time){boolean before(Cursor c){return time.isBefore(c.time)||time.equals(c.time)&&id.toString().compareTo(c.id.toString())<0;}}
 private record Cursor(Instant time,UUID id){static String encode(SortKey k){return Base64.getUrlEncoder().withoutPadding().encodeToString((k.time.toEpochMilli()+"|"+k.id).getBytes(StandardCharsets.UTF_8));}static Cursor decode(String s){if(s==null)return null;try{String[]p=new String(Base64.getUrlDecoder().decode(s),StandardCharsets.UTF_8).split("\\|",2);return new Cursor(Instant.ofEpochMilli(Long.parseLong(p[0])),UUID.fromString(p[1]));}catch(Exception e){throw new IllegalArgumentException("Invalid cursor");}}}
 public record FeedPage(List<ContentView> items,String nextCursor){}
}
